// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo2CFFj8sJvi38K2nGNDMNFA0ooBetBWs',
    appId: '1:1026331816736:web:df3674ffb1be3690dc1d45',
    messagingSenderId: '1026331816736',
    projectId: 'budgettracker-5d571',
    authDomain: 'budgettracker-5d571.firebaseapp.com',
    storageBucket: 'budgettracker-5d571.firebasestorage.app',
    measurementId: 'G-KR0JYBQ5WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMEG504SmsyRD1hhM6qkxfm_YtqV9SOqA',
    appId: '1:1026331816736:android:7084900a5cc2f9a5dc1d45',
    messagingSenderId: '1026331816736',
    projectId: 'budgettracker-5d571',
    storageBucket: 'budgettracker-5d571.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9e8_iyPOoSBaIKAR0kaV4AHumNmwyRJY',
    appId: '1:1026331816736:ios:b6a4c070f2eb7c56dc1d45',
    messagingSenderId: '1026331816736',
    projectId: 'budgettracker-5d571',
    storageBucket: 'budgettracker-5d571.firebasestorage.app',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9e8_iyPOoSBaIKAR0kaV4AHumNmwyRJY',
    appId: '1:1026331816736:ios:b6a4c070f2eb7c56dc1d45',
    messagingSenderId: '1026331816736',
    projectId: 'budgettracker-5d571',
    storageBucket: 'budgettracker-5d571.firebasestorage.app',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo2CFFj8sJvi38K2nGNDMNFA0ooBetBWs',
    appId: '1:1026331816736:web:4fbf878c534abceddc1d45',
    messagingSenderId: '1026331816736',
    projectId: 'budgettracker-5d571',
    authDomain: 'budgettracker-5d571.firebaseapp.com',
    storageBucket: 'budgettracker-5d571.firebasestorage.app',
    measurementId: 'G-KDWBCPZJBH',
  );
}
